import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { GLOBAL_CONFIG_FILE, LOOP_CONFIG_FILE, composeLoopConfig, globalConfigPath } from './config.js'
import { PRESET_NAMES, describePreset, isPresetName, type PresetName } from './presets.js'
import type { RichIO } from './ui/terminal.js'

export interface InitAnswers {
  readonly preset: PresetName
  readonly name: string
  readonly repo: string
  readonly baseBranch: string
  readonly workspaceId: string
  readonly teamKey: string
  readonly person: string
  readonly verifyCommand: string
  /** Written to the user's own `~/.agentskit/harness.yaml`, not to the repository. */
  readonly notifyCommand?: string
}

export interface InitQuestion {
  readonly key: keyof InitAnswers
  readonly question: string
  readonly options?: readonly { readonly label: string; readonly value: string; readonly hint?: string }[]
  readonly fallback: string
  readonly recommendation?: string
}

/**
 * The questions `loop init` grills, one per round, each with alternatives and a recommendation where one exists.
 *
 * Deliberately short: the preset answers everything that can be answered by the kind of project, so a human is
 * only asked what no default can know — who they are, which repository, which queue.
 */
export const initQuestions = (defaults: Partial<InitAnswers> = {}): readonly InitQuestion[] => [
  {
    key: 'preset', question: 'What kind of project is this?', fallback: defaults.preset ?? 'web-app',
    options: PRESET_NAMES.map((name) => ({ label: name, value: name, hint: describePreset(name) })),
    recommendation: 'web-app — the closest fit for a deployed service with a UI',
  },
  { key: 'name', question: 'Project name (what the loop calls it in comments and notifications)', fallback: defaults.name ?? '' },
  { key: 'repo', question: 'GitHub repository, as owner/name', fallback: defaults.repo ?? '' },
  { key: 'baseBranch', question: 'Integration branch — where the loop merges', fallback: defaults.baseBranch ?? 'main', recommendation: 'main, unless releases are cut from a different branch' },
  { key: 'workspaceId', question: 'Linear workspace id (`orca linear team list --workspace all --json`)', fallback: defaults.workspaceId ?? '' },
  { key: 'teamKey', question: 'Linear team key, e.g. ENG', fallback: defaults.teamKey ?? '' },
  { key: 'person', question: 'Whose queue does this machine drain? (Linear display name)', fallback: defaults.person ?? '' },
  { key: 'verifyCommand', question: 'The command a worker must pass before opening a PR', fallback: defaults.verifyCommand ?? '', recommendation: 'the preset already fills this; override only if this repo differs' },
]

const quote = (value: string): string => /^[\w./-]+$/.test(value) ? value : JSON.stringify(value)

/** The project file `loop init` writes: what this repository decides, and nothing the preset already says. */
export const renderInitConfig = (answers: InitAnswers): string => [
  `# Generated by \`ak-harness loop init\`. Everything not stated here comes from the "${answers.preset}" preset,`,
  '# then your ~/.agentskit/harness.yaml, and can be overridden per team or per machine. See the harness docs.',
  'schemaVersion: 1',
  `extends: ${answers.preset}`,
  '',
  'project:',
  `  name: ${quote(answers.name)}`,
  `  repo: ${quote(answers.repo)}`,
  `  baseBranch: ${quote(answers.baseBranch)}`,
  '',
  'linear:',
  `  workspaceId: ${quote(answers.workspaceId)}`,
  `  teamKey: ${quote(answers.teamKey)}`,
  `  person: ${quote(answers.person)}`,
  '',
  ...(answers.verifyCommand ? ['delivery:', `  verifyCommand: ${quote(answers.verifyCommand)}`, ''] : []),
].join('\n')

/**
 * The user's own file: identity, the models and providers they have, and where they want to be called. Never a
 * project's settings, and never a secret — a webhook URL lives in an environment variable, named here.
 */
export const renderGlobalConfig = (answers: InitAnswers): string => [
  '# Your own layer, outside every repository. It fills what a project does not state, and a project always wins.',
  ...STARTER_MODELS,
  ...(answers.notifyCommand
    ? ['notifications:', `  command: [${answers.notifyCommand.split(' ').map((part) => quote(part)).join(', ')}]`]
    : ['# notifications:', '#   webhook:', '#     urlEnv: LOOP_WEBHOOK_URL', '#   command: [terminal-notifier, -message, "{summary}"]']),
  '',
].join('\n')

/**
 * The providers a first run can actually use. They live in the user's layer, not the project's: which CLIs are
 * installed and logged in is a property of this machine and this person, not of the repository.
 */
const STARTER_MODELS: readonly string[] = [
  'models:',
  '  orchestrator: [[claude/opus, codex/gpt-5.6-sol]]',
  '  reviewer:     [[claude/opus, codex/gpt-5.6-sol]]',
  '  builder:      [[claude/sonnet, codex/gpt-5.6-luna]]',
  '  watcher:      [[claude/haiku]]',
  '  providers:',
  '    claude:',
  '      bin: claude',
  '      auth: subscription',
  '      tui: "claude --model {model} --permission-mode auto"',
  '      headless: [claude, -p, "{prompt}", --model, "{model}", --permission-mode, plan, --output-format, text]',
  '    codex:',
  '      bin: codex',
  '      auth: subscription',
  '      tui: "codex -m {model} -s workspace-write -a never"',
  '      headless: [codex, exec, -m, "{model}", -s, read-only, --skip-git-repo-check, "{prompt}"]',
  '',
]

export interface InitResult {
  readonly configPath: string
  readonly globalPath: string | null
  readonly answers: InitAnswers
  readonly wrote: readonly string[]
  readonly skipped: readonly string[]
}

export interface InitInput {
  readonly directory: string
  readonly io?: RichIO
  readonly answers?: Partial<InitAnswers>
  readonly env?: NodeJS.ProcessEnv
  /** Write the user's global file too, when it does not exist yet. */
  readonly writeGlobal?: boolean
  readonly force?: boolean
  readonly dryRun?: boolean
}

const answerFor = async (io: RichIO | undefined, question: InitQuestion, provided: string | undefined): Promise<string> => {
  if (provided !== undefined && provided !== '') return provided
  if (!io?.interactive) return question.fallback
  if (question.options?.length) {
    const chosen = await io.select(`${question.question}${question.recommendation ? ` (recommended: ${question.recommendation})` : ''}`, question.options.map((option) => ({ label: option.hint ? `${option.label} — ${option.hint}` : option.label, value: option.value })))
    return chosen ?? question.fallback
  }
  const typed = await io.text(`${question.question}${question.recommendation ? ` — ${question.recommendation}` : ''}`, question.fallback)
  return typed ?? question.fallback
}

/**
 * Grill the human, then write `loop.config.yaml` (and, when asked, the user's global file).
 *
 * It refuses to overwrite an existing config without `force`: a generated file landing on top of a tuned one is
 * the kind of help nobody asks for twice.
 */
export const runLoopInit = async (input: InitInput): Promise<InitResult> => {
  const configPath = resolve(input.directory, LOOP_CONFIG_FILE)
  const answers: Record<string, string> = {}
  for (const question of initQuestions(input.answers)) {
    answers[question.key] = await answerFor(input.io, question, input.answers?.[question.key] as string | undefined)
  }
  if (!isPresetName(answers['preset'])) answers['preset'] = 'web-app'
  const resolved = answers as unknown as InitAnswers

  const wrote: string[] = []
  const skipped: string[] = []
  const text = renderInitConfig(resolved)
  // Validate the *composition* — preset, the user's layer, this file — because that is what the loop will load.
  // A project file alone is not a valid config by design: the models a machine can use belong to the user.
  const existingGlobal = globalConfigPath(input.env ?? process.env)
  const globalText = existsSync(existingGlobal) ? readFileSync(existingGlobal, 'utf8') : renderGlobalConfig(resolved)
  composeLoopConfig({ globalText, text })

  if (existsSync(configPath) && !input.force) skipped.push(`${configPath} already exists (pass --force to replace it)`)
  else if (!input.dryRun) { mkdirSync(dirname(configPath), { recursive: true }); writeFileSync(configPath, text, 'utf8'); wrote.push(configPath) }
  else wrote.push(`${configPath} (dry-run)`)

  let globalPath: string | null = null
  if (input.writeGlobal) {
    globalPath = globalConfigPath(input.env ?? process.env)
    if (existsSync(globalPath) && !input.force) skipped.push(`${globalPath} already exists; left as it is`)
    else if (!input.dryRun) { mkdirSync(dirname(globalPath), { recursive: true }); writeFileSync(globalPath, renderGlobalConfig(resolved), 'utf8'); wrote.push(globalPath) }
    else wrote.push(`${globalPath} (dry-run)`)
  }
  return { configPath, globalPath, answers: resolved, wrote, skipped }
}

export const GLOBAL_CONFIG_BASENAME = GLOBAL_CONFIG_FILE
